---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: nimishgsk17/calculator:latest
        source: pull

    - name: Stop existing container
      shell: docker stop Calculator || true

    - name: Remove existing container
      shell: docker rm Calculator || true

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name Calculator nimishgsk17/calculator